# Generated by Django 3.2 on 2021-05-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_multistepformmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultiStepFormModel',
            new_name='request',
        ),
    ]
