# Generated by Django 3.2 on 2021-05-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210518_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(default='0000000', editable=False, max_length=50),
        ),
    ]
